dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage
branches:
   only: development
notifications:
   email:
      recipients:
      - williamwalldeveloper@gmail.com
      on_success: never
      on_failure: always