dist: trusty
language: node_js
node_js:
- stable
 branches:
    only: development
  notifications:
     email:
        recipients:
        - one@example.com      # change to your own address
        - other@example.com    # uae other (optional)
        on_success: never        # default: change
        on_failure: always       # default: always